
package cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Conversor", targetNamespace = "http://controle/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Conversor {


    /**
     * 
     * @param grau
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "celciusToKelvin", targetNamespace = "http://controle/", className = "cliente.CelciusToKelvin")
    @ResponseWrapper(localName = "celciusToKelvinResponse", targetNamespace = "http://controle/", className = "cliente.CelciusToKelvinResponse")
    @Action(input = "http://controle/Conversor/celciusToKelvinRequest", output = "http://controle/Conversor/celciusToKelvinResponse")
    public String celciusToKelvin(
        @WebParam(name = "grau", targetNamespace = "")
        String grau);

    /**
     * 
     * @param grau
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "kelvinToCelcius", targetNamespace = "http://controle/", className = "cliente.KelvinToCelcius")
    @ResponseWrapper(localName = "kelvinToCelciusResponse", targetNamespace = "http://controle/", className = "cliente.KelvinToCelciusResponse")
    @Action(input = "http://controle/Conversor/kelvinToCelciusRequest", output = "http://controle/Conversor/kelvinToCelciusResponse")
    public String kelvinToCelcius(
        @WebParam(name = "grau", targetNamespace = "")
        String grau);

}
